'use client';

import "./globals.css";
import Providers from "./providers";
import { AuthProvider } from "@/context/AuthContext";
import { Provider } from "react-redux";
import store from "@/app/redux/store";
import { nunito } from "@/app/ui/fonts";
import { useEffect } from "react";
import { setUserLocation as setReduxUserLocation } from "@/app/redux/app/appSlice";
import Toast from "@/app/ui/toast-container";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}) {
  const getUserLocation = () => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          store.dispatch(setReduxUserLocation({
            lat: position.coords.latitude,
            lng: position.coords.longitude,
          }));
        },
        (error) => {
          console.error("Error getting location:", error);
        }
      );
    } else {
      console.error("Geolocation is not supported by this browser.");
    }
  };

  useEffect(() => {
    getUserLocation();
  }, []);

  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <Provider store={store}>
          <AuthProvider>
            <Toast />
            <Providers>{children}</Providers>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
